package newpackage;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author hunor
 */
//import *;
import MainDashboard.MainDashboard;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import newpackage.CharacterEditor.ComicObjectRenderer;
import ro.madarash.kepregeny_project.*;

public class EditionEditor extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditionEditor.class.getName());

    /**
     * Creates new form EditionEditor
     */
    
    private ComicBook parentComicBook;
    
    public EditionEditor(java.awt.Frame parent, boolean modal, 
                         ComicBook parentComic, List<Publisher> allPublishers) {
        
        super(parent, modal);
        
        // --- NEW: Save the parent comic ---
        if (parentComic == null) {
            throw new IllegalArgumentException("parentComic cannot be null.");
        }
        this.parentComicBook = parentComic;
        
        // This method builds the form's layout and components
        initComponents();

        // --- NEW: Set the Custom Renderer for the JComboBox ---
        publisherComboBox.setRenderer(new ComicObjectRenderer());
        
        // --- NEW: Populate the JComboBox ---
        publisherComboBox.setModel(new DefaultComboBoxModel<>(
                allPublishers.toArray(new Publisher[0])
        ));

        // Set the title to show which comic is being edited
        setTitle("Add Edition for: " + parentComicBook.getTitle());

        // Center the dialog on top of its parent (MainDashboard)
        setLocationRelativeTo(parent);
    }
    
    /**
     * Helper method to load the list of publishers into the ComboBox.
     */
    private void populatePublisherComboBox(List<Publisher> publishers) {
        // Create a model that will hold our Publisher objects
        DefaultComboBoxModel<Publisher> model = new DefaultComboBoxModel<>();
        
        // Add all available publishers from the list
        for (Publisher pub : publishers) {
            model.addElement(pub);
        }
        
        // Set this model on our combo box
        publisherComboBox.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        mainFormPanel = new javax.swing.JPanel();
        editionNameLabel = new javax.swing.JLabel();
        editionNameField = new javax.swing.JTextField();
        publisherLabel = new javax.swing.JLabel();
        isbnField = new javax.swing.JTextField();
        publisherComboBox = new javax.swing.JComboBox<>();
        isbnLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(saveButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        mainFormPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        mainFormPanel.setLayout(new java.awt.GridBagLayout());

        editionNameLabel.setText("Edition Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainFormPanel.add(editionNameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainFormPanel.add(editionNameField, gridBagConstraints);

        publisherLabel.setText("Publisher:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainFormPanel.add(publisherLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainFormPanel.add(isbnField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainFormPanel.add(publisherComboBox, gridBagConstraints);

        isbnLabel.setText("ISBN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainFormPanel.add(isbnLabel, gridBagConstraints);

        dateLabel.setText("Publication Date:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainFormPanel.add(dateLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainFormPanel.add(dateField, gridBagConstraints);

        getContentPane().add(mainFormPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String editionName = editionNameField.getText();
        String isbn = isbnField.getText();
        String dateStr = dateField.getText();
        
        // Get the *selected objects* from the dropdown
        Publisher selectedPublisher = (Publisher) publisherComboBox.getSelectedItem();

        // 2. Validate data
        if (editionName.isBlank()) {
            JOptionPane.showMessageDialog(this, "Edition Name cannot be empty.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (selectedPublisher == null) {
            JOptionPane.showMessageDialog(this, "You must select a Publisher.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 3. Parse the date (this is a simple, strict parser)
        Date pubDate;
        try {
            // Force the user to use YYYY-MM-DD format
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            sdf.setLenient(false); // Don't allow "2023-02-30"
            pubDate = sdf.parse(dateStr);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, 
                    "Invalid date format. Please use YYYY-MM-DD.", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. Create a new Edition object (from your logic JAR)
        // ** NEW: We use this.parentComicBook instead of getting from a dropdown **
        Edition newEdition = new Edition(editionName, pubDate, isbn, selectedPublisher, this.parentComicBook);
        
        // 5. Link the edition to its parent comic
        this.parentComicBook.addEdition(newEdition);
        
        System.out.println("Saving new edition: " + newEdition.getEditionName() + " for comic " + this.parentComicBook.getTitle());

        // 6. TODO: Add the 'newEdition' to your main data list in MainDashboard
        // ((MainDashboard) getParent()).addEditionToList(newEdition);
        //((MainDashboard) getParent()).refreshTable();
        
        // 7. Close the dialog
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(EditionEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the dialog for testing */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                // --- Create Dummy Data for Testing ---
                
                // ** NEW: We must create a parent comic to pass to the constructor **
                ComicBook testComic = new ComicBook("The Killing Joke", "Superhero");
                //ComicBook testComic = null; // Replace with a real object to test
                
                List<Publisher> testPublishers = new ArrayList<>();
                testPublishers.add(new Publisher("DC Comics", "USA"));
                testPublishers.add(new Publisher("Marvel Comics", "USA"));
                
                // --- Create the dialog and pass the test data ---
                // The main frame (parent)
                JFrame testFrame = new javax.swing.JFrame();
                
                // Check if testComic is null before creating
                if (testComic == null) {
                    System.err.println("Cannot run test: testComic is null. Please instantiate it in the main method.");
                    System.exit(1);
                }
                
                EditionEditor dialog = new EditionEditor(testFrame, true, testComic, testPublishers);
                
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    class ComicObjectRenderer extends DefaultListCellRenderer {
        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index,
                                                      boolean isSelected, boolean cellHasFocus) {
            // Get the default component (a JLabel)
            Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            
            // Check the type of the object and set the text accordingly
            if (value instanceof Publisher) {
                setText(((Publisher) value).getName());
            } else if (value instanceof ComicBook) {
                setText(((ComicBook) value).getTitle());
            } 
            // (Add other 'else if' for Writer, Artist, Character as needed)
            
            return c;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField editionNameField;
    private javax.swing.JLabel editionNameLabel;
    private javax.swing.JTextField isbnField;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JPanel mainFormPanel;
    private javax.swing.JComboBox<Publisher> publisherComboBox;
    private javax.swing.JLabel publisherLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
