/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package newpackage;

/**
 *
 * @author hunor
 */

import MainDashboard.MainDashboard;
import ro.madarash.kepregeny_project.*;
import javax.swing.*;
import java.awt.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class PublisherEditor extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PublisherEditor.class.getName());
    
    // --- NEW: Field to store the publisher being edited ---
    private Publisher publisherToEdit;
    
    public PublisherEditor(java.awt.Frame parent, boolean modal) {
        // Call the parent JDialog's constructor
        super(parent, modal);

        // This method builds the form's layout and components
        initComponents();
        
        this.setSize(700, 600);

        // Center the dialog on top of its parent (MainDashboard)
        setLocationRelativeTo(parent);
        
        // publisherToEdit is null, so we are in "Create" mode
        this.publisherToEdit = null;
    }
    
    /**
     * --- NEW: "EDIT MODE" Constructor ---
     * Creates new form PublisherEditor to edit an existing publisher.
     */
    public PublisherEditor(java.awt.Frame parent, boolean modal, Publisher publisherToEdit) {
        // Call the other constructor
        this(parent, modal); 
        
        // Set the publisher to edit
        this.publisherToEdit = publisherToEdit;
        
        // Change the window title
        setTitle("Edit Publisher");
        
        // Load its data into the form
        loadDataForEdit();
    }
    
    /**
     * --- NEW: Helper method to load data into fields ---
     */
    private void loadDataForEdit() {
        if (this.publisherToEdit != null) {
            nameField.setText(this.publisherToEdit.getName());
            countryField.setText(this.publisherToEdit.getCountry());
            
            
            if (this.publisherToEdit.getFoundationYear() != null) {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                foundationTextField.setText(sdf.format(this.publisherToEdit.getFoundationYear()));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        mainFormPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        countryLabel = new javax.swing.JLabel();
        countryField = new javax.swing.JTextField();
        foundationLabel = new javax.swing.JLabel();
        foundationTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Publisher Editor");
        getContentPane().setLayout(new java.awt.BorderLayout(50, 50));

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(saveButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        mainFormPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        mainFormPanel.setLayout(new java.awt.GridBagLayout());

        nameLabel.setText("Publisher Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainFormPanel.add(nameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainFormPanel.add(nameField, gridBagConstraints);

        countryLabel.setText("Country of Origin:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainFormPanel.add(countryLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainFormPanel.add(countryField, gridBagConstraints);

        foundationLabel.setText("Foundation Year");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainFormPanel.add(foundationLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainFormPanel.add(foundationTextField, gridBagConstraints);

        getContentPane().add(mainFormPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        // 1. Get the data from the text fields
        String publisherName = nameField.getText();
        String country = countryField.getText();
        String dateStr = foundationTextField.getText();

        // 2. Validate the data
        if (publisherName.isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Publisher Name cannot be empty.",
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
            return; // Stop
        }
        
        Date foundDate;
        try {
            // Force the user to use YYYY-MM-DD format
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            sdf.setLenient(false); // Don't allow "2023-02-30"
            foundDate = sdf.parse(dateStr);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, 
                    "Invalid date format. Please use YYYY-MM-DD.", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Check if we are in "Edit Mode" or "Create Mode"
        if (publisherToEdit != null) {
            // --- EDIT MODE ---
            logger.info("Updating publisher: " + publisherToEdit.getName());
            // Update the existing object's properties
            publisherToEdit.setName(publisherName);
            publisherToEdit.setCountry(country);
            publisherToEdit.setFoundationYear(foundDate);
            
        } else {
            // --- CREATE MODE ---
            // Create a new Publisher object
            Publisher newPublisher = new Publisher(publisherName, country, foundDate);
            logger.info("Saving new publisher: " + publisherName);

            // Add the new publisher to the main list
            ((MainDashboard) getParent()).addPublisher(newPublisher);
        }

        // 4. Close the dialog
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * Called when the "Save" button is clicked.
     
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // 1. Get the data from the text fields
        String publisherName = nameField.getText();
        String country = countryField.getText();
        String dateStr = foundationTextField.getText();

        // 2. Validate the data
        if (publisherName.isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Publisher Name cannot be empty.",
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
            return; // Stop
        }
        
        Date foundDate;
        try {
            // Force the user to use YYYY-MM-DD format
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            sdf.setLenient(false); // Don't allow "2023-02-30"
            foundDate = sdf.parse(dateStr);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, 
                    "Invalid date format. Please use YYYY-MM-DD.", 
                    "Validation Error", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Check if we are in "Edit Mode" or "Create Mode"
        if (publisherToEdit != null) {
            // --- EDIT MODE ---
            logger.info("Updating publisher: " + publisherToEdit.getName());
            // Update the existing object's properties
            publisherToEdit.setName(publisherName);
            publisherToEdit.setCountry(country);
            publisherToEdit.setFoundationYear(foundDate);
            
        } else {
            // --- CREATE MODE ---
            // Create a new Publisher object
            Publisher newPublisher = new Publisher(publisherName, country, foundDate);
            logger.info("Saving new publisher: " + publisherName);

            // Add the new publisher to the main list
            ((MainDashboard) getParent()).addPublisher(newPublisher);
        }

        // 4. Close the dialog
        this.dispose();
    }
*/
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(PublisherEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog for testing */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Create a dialog with a 'null' parent and 'true' modality
                PublisherEditor dialog = new PublisherEditor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField countryField;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JLabel foundationLabel;
    private javax.swing.JTextField foundationTextField;
    private javax.swing.JPanel mainFormPanel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
