/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainDashboard;

/**
 *
 * @author hunor
 */
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import newpackage.EditionEditor;
import newpackage.CharacterEditor;
import newpackage.ComicBookEditor;
import newpackage.CreatorEditor;
import ro.madarash.kepregeny_project.*;


public class MainDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());

    /**
     * Creates new form MainDashboard
     */
    public MainDashboard() {
        initComponents();
        
        // Set the window to appear in the center of the screen
        setLocationRelativeTo(null);

        // --- Demo Data ---
        // Let's add some sample data to the table to see how it looks
        DefaultTableModel model = (DefaultTableModel) mainItemTable.getModel();
        model.addRow(new Object[]{"Action Comics #1", "Comic Book", "DC Comics"});
        model.addRow(new Object[]{"Amazing Fantasy #15", "Comic Book", "Marvel"});
        model.addRow(new Object[]{"Spider-Man", "Character", "Peter Parker"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainItemTable = new javax.swing.JTable();
        detailsPanel = new javax.swing.JPanel();
        detailsTitleLabel = new javax.swing.JLabel();
        buttomButtonPanel = new javax.swing.JPanel();
        addCharacterButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        addComicBookButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuItemExit = new javax.swing.JMenuItem();
        addMenu = new javax.swing.JMenu();
        menuItemAddComic = new javax.swing.JMenuItem();
        menuItemAddCharacter = new javax.swing.JMenuItem();
        menuItemAddCreator = new javax.swing.JMenuItem();
        menuItemAddPublisher = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comic Book Database Dashboard");
        setMinimumSize(new java.awt.Dimension(700, 500));

        mainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mainItemTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title / Name", "Type", "Publisher / Affiliation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mainItemTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        mainItemTable.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(mainItemTable);

        detailsTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detailsTitleLabel.setText("Select an item to see details");

        javax.swing.GroupLayout detailsPanelLayout = new javax.swing.GroupLayout(detailsPanel);
        detailsPanel.setLayout(detailsPanelLayout);
        detailsPanelLayout.setHorizontalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailsTitleLabel)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        detailsPanelLayout.setVerticalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailsTitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addCharacterButton.setText("Add New Character");
        addCharacterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCharacterButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit Selected Item");

        deleteButton.setText("Delete Selected Item");

        addComicBookButton.setText("Add New Comic Book");
        addComicBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComicBookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttomButtonPanelLayout = new javax.swing.GroupLayout(buttomButtonPanel);
        buttomButtonPanel.setLayout(buttomButtonPanelLayout);
        buttomButtonPanelLayout.setHorizontalGroup(
            buttomButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttomButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addComicBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCharacterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        buttomButtonPanelLayout.setVerticalGroup(
            buttomButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttomButtonPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(buttomButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addComicBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCharacterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        addCharacterButton.getAccessibleContext().setAccessibleName("jAddNewCharacterButton");
        editButton.getAccessibleContext().setAccessibleName("jEditSelectedItemButton");
        deleteButton.getAccessibleContext().setAccessibleName("jDeleteSelectedItemButton");
        addComicBookButton.getAccessibleContext().setAccessibleName("jComicBookEditorButton");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(buttomButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(detailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttomButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(detailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        detailsPanel.getAccessibleContext().setAccessibleName("JDetailsPanel");

        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemExit);

        menuBar.add(fileMenu);
        fileMenu.getAccessibleContext().setAccessibleName("jExit");

        addMenu.setText("Add New");

        menuItemAddComic.setText("Add Comic");
        menuItemAddComic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddComicActionPerformed(evt);
            }
        });
        addMenu.add(menuItemAddComic);

        menuItemAddCharacter.setText("Add Character");
        addMenu.add(menuItemAddCharacter);

        menuItemAddCreator.setText("Add Creator");
        addMenu.add(menuItemAddCreator);

        menuItemAddPublisher.setText("Add Publisher");
        addMenu.add(menuItemAddPublisher);

        menuBar.add(addMenu);
        addMenu.getAccessibleContext().setAccessibleName("jAddNew");

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.getAccessibleContext().setAccessibleName("jPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCharacterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCharacterButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Opening Character Editor...");
        
        CharacterEditor charEditor = new CharacterEditor(this, true);
        charEditor.setVisible(true);
        EditionEditor edti = new EditionEditor(this,true);
        
                
        // After the dialog closes, you would refresh the table:
        //refreshTableData();
    }//GEN-LAST:event_addCharacterButtonActionPerformed

    private void addComicBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComicBookButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Opening Comic Book Editor...");
        // 1. Create an instance of your editor dialog
        // The 'this' and 'true' make it a "modal" dialog,
        // which blocks the main window until you close the pop-up.
        ComicBookEditor comicEditor = new ComicBookEditor(this, true);

        // 2. Make the dialog visible
        comicEditor.setVisible(true);

        // 3. (After the user clicks 'Save' or 'Cancel' and the dialog closes)
        // You can add code here to refresh your main JTable
        // to show the new comic that was added.
    }//GEN-LAST:event_addComicBookButtonActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemAddComicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddComicActionPerformed
        // TODO add your handling code here:
        addComicBookButtonActionPerformed(evt);
    }//GEN-LAST:event_menuItemAddComicActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCharacterButton;
    private javax.swing.JButton addComicBookButton;
    private javax.swing.JMenu addMenu;
    private javax.swing.JPanel buttomButtonPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JLabel detailsTitleLabel;
    private javax.swing.JButton editButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainItemTable;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemAddCharacter;
    private javax.swing.JMenuItem menuItemAddComic;
    private javax.swing.JMenuItem menuItemAddCreator;
    private javax.swing.JMenuItem menuItemAddPublisher;
    private javax.swing.JMenuItem menuItemExit;
    // End of variables declaration//GEN-END:variables
}
